### ISSUE TITLE
[feature] 寻找新的pairs接口

### ISSUE THREAD

**Issue by uerax** [uerax/all-in-one-bot#111]
Dexscreener允许的次数多一些 但是有大量token无法找到pairs
Honeypot允许的次数太少 暂时没有出现找不到pairs的情况

**Comment by bakasine** [comment]
目前有4个pairs获取接口, 采用和apikey同一套轮询 或者是链式, 当请求次数满了被banip后采用另一个api

**Comment by uerax** [comment]
改变策略 换新的kline接口以省略pair获取
