### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by diqiuren8881** [uerax/all-in-one-bot#114]
你好，这个项目还在做吗？下载下来的exe文档 打开后出现一个框后就退出了，是怎么回事？我是小白其他运行方式不怎么会

**Comment by bakasine** [comment]
all-in-one-bot.yml 把这个配置文件下载放到exe同目录, 填你的tg机器人id和你的tg的id

**Comment by diqiuren8881** [comment]
https://github.com/uerax/all-in-one-bot/assets/148855741/1146c5ae-0bcd-4098-bada-5cef6d5cbbaf

我这样操作是对的吗  打开exe文件后依然出现弹框

**Comment by bakasine** [comment]
> 9.mp4 
> 我这样操作是对的吗 打开exe文件后依然出现弹框
![image](https://github.com/uerax/all-in-one-bot/assets/8407699/341e222f-1ef4-4e47-9f3a-4e41dae3d28b)
配置文件这两项必填, 不知道填什么看readme

**Comment by diqiuren8881** [comment]
![131112151408](https://github.com/uerax/all-in-one-bot/assets/148855741/acb4ac8b-b33e-4b57-bbdd-4558825f9674)
我填写了 必填项  点击.exe文件，依然像上次一样的情况，这是怎么回事

**Comment by uerax** [comment]
> ![131112151408](https://github.com/uerax/all-in-one-bot/assets/148855741/acb4ac8b-b33e-4b57-bbdd-4558825f9674)
> 
> 我填写了 必填项  点击.exe文件，依然像上次一样的情况，这是怎么回事

冒号后面要空格，还有你用国内的网络连不上tg的服务器

**Comment by diqiuren8881** [comment]
https://github.com/uerax/all-in-one-bot/assets/148855741/f7b027e4-333f-4a2a-9361-803dd6e15041

我加了空格后是 用来vpn之后出来这个黑框 但是里面无法编辑 ，无法键入
