### ISSUE TITLE
请求帮助[feature] 

### ISSUE THREAD

**Issue by hbyswangfei** [uerax/all-in-one-bot#115]
您好我在网上看到您写的这个程序，我觉得对我非常有用。但是我没有程序基础，下载下来的无论是源码包还是编译的exe文件都不会使用，我按照文章里写的步骤配置好了Local Telegram Api，能不能和您请教一下具体该如何运行他们，文章里的命令应该在哪里输入。如果有空的话请给我留言或者给个联系方式可以吗？

**Comment by uerax** [comment]
补充你的信息
操作系统
配置文件
还有启动失败的界面

**Comment by hbyswangfei** [comment]
我是windows11 64位的系统，然后我按照说明能看懂的地方，把能安装的都装了，下图里的步骤算是都正常完成了，但是在https://my.telegram.org/里我多次尝试，好像无论填写什么内容都报告ERROR，所以没有得到ID


<img width="938" alt="1" src="https://github.com/uerax/all-in-one-bot/assets/157203791/c7bb0b88-2b2e-4e96-86f5-47489a002803">


<img width="557" alt="7" src="https://github.com/uerax/all-in-one-bot/assets/157203791/187e4def-6253-4fc5-877e-12f169feef6f">

然后下载了您编译的exe文件发现直接运行闪退，用cmd打开提示没有输入TOKEN，我也不知道在哪里配置只能停止了。
按照说明的指引我申请好了telegram机器人token和chatID，和他对话没有反应的。
然后我下载了源代码zip包，解压放在D盘里根目录里，yml的配置文件我填入机器人给的token和id码，其他未做改动。


<img width="736" alt="2" src="https://github.com/uerax/all-in-one-bot/assets/157203791/9fdd1514-87a4-446c-aa33-656780f9a358">

因为不大懂得怎么使用，我把所有文件都双击运行了一遍，除了一些文本的代码文件。有三个.sh后缀的可以运行。
autow.sh打开后会自动关闭，build.sh打开会提示输入版本号，install.sh是有反应的。窗口如下图，但是除了2 和8两个配置文件的选项，其他的都是瞬间关闭。通过多次打开隐约看到提示为command no found。
然后我按照网上搜寻到的资料，尝试在all in one bot文件夹内空白处右键选择选择 此处打开open base,然后将说明里的命令逐条复制进去运行了一遍，返回结果好像都不正常

<img width="584" alt="5" src="https://github.com/uerax/all-in-one-bot/assets/157203791/a2390e29-f46c-4d3d-b3bb-c248de404126">

使用bash -c "$(curl -L https://raw.githubusercontent.com/uerax/all-in-one-bot/master/install.sh)" @这条命令会打开和install.sh一样的界面

<img width="471" alt="6" src="https://github.com/uerax/all-in-one-bot/assets/157203791/f6b26480-8f14-486e-be57-f9cbeed2db96">

后面就无法继续了，我上网查了很久，因为这方面不了解我甚至不知道这是什么语言编译的程序，也没有什么收获，所以来寻求下您的帮助。
所以我想知道如何正确运行这个程序，以及日常使用是否每次打开电脑要先运行特定程序，然后才能在telegram里面使用吗？
万分感谢您的回复！！

**Comment by uerax** [comment]
首先脚本是针对linux写的没有做win的兼容，所以你要做的是这几个步骤
- 获取你的tg机器人token
- 下载win后缀的aio.exe
- 下载配置文件放在aio.exe同目录一下
- 在配置文件填写你的机器人token和你的chatid
- 双击打开aio

**Comment by hbyswangfei** [comment]
我尝试用这方式还是无法运行，可能是系统无法兼容，虽然很可惜，很感谢您的解答
