### ISSUE TITLE
查询结果不一致

### ISSUE THREAD

**Issue by uerax** [uerax/all-in-one-bot#34]
0x3fc59a5e402071449010127181c2c1127a5572aa 0x0607a9844472e8ef1058dc33096ace550cb65909
![image](https://github.com/uerax/all-in-one-bot/assets/44748971/bfaaf7ff-ad5e-4830-babc-9303a3b47a77)

**Comment by bakasine** [comment]
免费接口每秒只能做5次查询, 由于还有其他价格追踪调用, 导致请求超过5条. 所以量正常的情况下计算出来的价格有所不同

**Comment by bakasine** [comment]
方案1: 超过次数后查询失败等待一段时间后重新查询 
方案2: 一个账号可以申请3个key,每个key每秒可以查询5条, 申请多个账号填写多条key解决该问题, 需要写一个轮询获取key算法或者随机取key
