### ISSUE TITLE
能不能添加多个免费的APIkey，一个免费次数用完就调另一个[feature] 

### ISSUE THREAD

**Issue by Heresy-dd** [uerax/all-in-one-bot#94]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by uerax** [comment]
etherscan的key？这个已经支持了可以看配置文件描述自己添加
他一个key每秒免费5次，我这边一些分析功能每秒qps在20-30以上，用免费的key建议最少填10个
